version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogscript
      # Add your other env variables here

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo-data:
  jenkins-data: